// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/proto/tinylink.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdGenerator_GenerateId_FullMethodName = "/proto.IdGenerator/GenerateId"
)

// IdGeneratorClient is the client API for IdGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义 ID 生成器服务
type IdGeneratorClient interface {
	// 定义一个 RPC 方法，叫 GenerateId
	// 它接收一个空请求 (Empty)
	// 并返回一个包含新 ID 的响应 (GenerateIdResponse)
	GenerateId(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenerateIdResponse, error)
}

type idGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewIdGeneratorClient(cc grpc.ClientConnInterface) IdGeneratorClient {
	return &idGeneratorClient{cc}
}

func (c *idGeneratorClient) GenerateId(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenerateIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateIdResponse)
	err := c.cc.Invoke(ctx, IdGenerator_GenerateId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdGeneratorServer is the server API for IdGenerator service.
// All implementations must embed UnimplementedIdGeneratorServer
// for forward compatibility.
//
// 定义 ID 生成器服务
type IdGeneratorServer interface {
	// 定义一个 RPC 方法，叫 GenerateId
	// 它接收一个空请求 (Empty)
	// 并返回一个包含新 ID 的响应 (GenerateIdResponse)
	GenerateId(context.Context, *Empty) (*GenerateIdResponse, error)
	mustEmbedUnimplementedIdGeneratorServer()
}

// UnimplementedIdGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdGeneratorServer struct{}

func (UnimplementedIdGeneratorServer) GenerateId(context.Context, *Empty) (*GenerateIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateId not implemented")
}
func (UnimplementedIdGeneratorServer) mustEmbedUnimplementedIdGeneratorServer() {}
func (UnimplementedIdGeneratorServer) testEmbeddedByValue()                     {}

// UnsafeIdGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdGeneratorServer will
// result in compilation errors.
type UnsafeIdGeneratorServer interface {
	mustEmbedUnimplementedIdGeneratorServer()
}

func RegisterIdGeneratorServer(s grpc.ServiceRegistrar, srv IdGeneratorServer) {
	// If the following call pancis, it indicates UnimplementedIdGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdGenerator_ServiceDesc, srv)
}

func _IdGenerator_GenerateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGeneratorServer).GenerateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdGenerator_GenerateId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGeneratorServer).GenerateId(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IdGenerator_ServiceDesc is the grpc.ServiceDesc for IdGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IdGenerator",
	HandlerType: (*IdGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateId",
			Handler:    _IdGenerator_GenerateId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/tinylink.proto",
}
